name: ci.yml
env:
  CI: true
  NODE_VERSION: 22

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write # for dependabot updates

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun ci
      - name: Check formatting
        run: bun run format
      - name: Lint
        run: bun run lint
      - name: Type check
        run: bun run check
      - name: Run unit tests
        run: bun run test -- --run

  example-sveltekit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
      - name: Install example dependencies
        run: bun ci
        working-directory: examples/sveltekit
      - name: Run integration tests
        run: bun run test
        working-directory: examples/sveltekit
      - name: Build example app
        run: bun run build
        working-directory: examples/sveltekit

  example-tanstack-start:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: oven-sh/setup-bun@v2
      - name: Install example dependencies
        run: bun ci
        working-directory: examples/tanstack-start
      - name: Run integration tests
        run: bun run test
        working-directory: examples/tanstack-start
      - name: Build example app
        run: bun run build
        working-directory: examples/tanstack-start

  publish-to-npm-public:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [unit-tests, example-sveltekit, example-tanstack-start]
    # Avoid running for non-main branches and non-merge events like new pull requests.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - name: Publish to NPM, if version was incremented
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          ignore-scripts: false # Allows the project's `prepublishOnly` script.
          strategy: upgrade # Publish only if the version was incremented.
